github.com:
    users:
        nonotor67:
            oauth_token: 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
    git_protocol: ssh
    user: nonotor67
    oauth_token: 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
