github.com:
    users:
        nonotor67:
            oauth_token: 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
    git_protocol: ssh
    user: nonotor67
    oauth_token: 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
