#! /usr/bin/env zsh

brightnessctl -s

if [ "$(brightnessctl g)" -gt "$($(brightnessctl max) / 2)" ]; then
  brightnessctl s 50%
fi

hyprlock
brightnessctl -r
notify-send 'Arch' "Welcome back $(whoami)\!"

