#!/bin/sh

# Global settings
bspc config normal_border_color '#4a4a4a'
bspc config active_border_color '#848484'
bspc config focused_border_color '#668e89'
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 8ms

# Desktop settings
bspc config window_gap 8

# Node settings
bspc config border_width 3

# Rules
bspc rule -a flameshot border=off
bspc rule -a *:*:splash state=floating
bspc rule -a Unity:*:Unity state=floating

# Initialize desktops
init_desktops() {
    local monitors=($(xrandr --listactivemonitors | tail -n +2 | awk '{ print $4; }'))
    local num_desktops_per_monitor="$((10 / "${#monitors[@]}"))"
    local monitor_seq_start=1

    for monitor in "${monitors[@]}"; do
        monitor_seq_end="$(("${monitor_seq_start}" + "${num_desktops_per_monitor}" - 1))"
        bspc monitor "${monitor}" -d $(seq "${monitor_seq_start}" "${monitor_seq_end}")
        monitor_seq_start="$(("${monitor_seq_start}" + "${num_desktops_per_monitor}"))"
    done
}

init_desktops

# Startup notification
source /etc/os-release
notify-send -u low "${PRETTY_NAME}" "$(uname -sr)"
