[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4a4a4a"
blue = "#b5cdff"
cyan = "#bcecff"
green = "#d4e5b9"
magenta = "#d8c0e8"
red = "#ff8787"
white = "#ffffff"
yellow = "#f9f1a2"

[colors.normal]
black = "#1a1a1a"
blue = "#678fe0"
cyan = "#5fe2fc"
green = "#adcc80"
magenta = "#baa5b7"
red = "#e27878"
white = "#cccccc"
yellow = "#ffdb9e"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[window]
opacity = 0.65

[window.dimensions]
columns = 92
lines = 24

[window.padding]
x = 8
y = 8

# set font size
[font]
size = 10
